### ISSUE TITLE
ResourceRoleRepository.getRoleByCode should not throw NullPointerException

### ISSUE THREAD

**Issue by gorbunkov** [jmix-projects/jmix-security#145]
Currently, the `getRoleByCode()` method of `ResourceRoleRepository` and `RowLevelRoleRepository` throws NullPointerException in case the role with the given code doesn't exist. It seems that this is not a correct exception type.

**Comment by Flaurite** [comment]
Fixed in: https://github.com/Haulmont/jmix-security/issues/110
